#!/bin/sh

stow . -v -t ~ \
    --ignore=submodule-update \
    --ignore=.gitmodules \
    --ignore=.git \
    --ignore=install-symlinks \
    --ignore=colorschemes \
    --ignore=README.md

ln -v -s ${PWD}/.config/geany/colorschemes/colorschemes ~/.config/geany/colorschemes
